var annotated =
[
    [ "charliesoft", null, [
      [ "AlgoPerformance", "classcharliesoft_1_1_algo_performance.html", "classcharliesoft_1_1_algo_performance" ],
      [ "AnyTypeWidget", "classcharliesoft_1_1_any_type_widget.html", "classcharliesoft_1_1_any_type_widget" ],
      [ "Block", "classcharliesoft_1_1_block.html", "classcharliesoft_1_1_block" ],
      [ "BlockLink", "structcharliesoft_1_1_block_link.html", "structcharliesoft_1_1_block_link" ],
      [ "ConditionConfigurator", "classcharliesoft_1_1_condition_configurator.html", "classcharliesoft_1_1_condition_configurator" ],
      [ "ConditionLinkRepresentation", "classcharliesoft_1_1_condition_link_representation.html", "classcharliesoft_1_1_condition_link_representation" ],
      [ "ConditionOfRendering", "classcharliesoft_1_1_condition_of_rendering.html", "classcharliesoft_1_1_condition_of_rendering" ],
      [ "Converter", "classcharliesoft_1_1_converter.html", "classcharliesoft_1_1_converter" ],
      [ "CreateParamWindow", "classcharliesoft_1_1_create_param_window.html", "classcharliesoft_1_1_create_param_window" ],
      [ "DraggableContainer", "classcharliesoft_1_1_draggable_container.html", "classcharliesoft_1_1_draggable_container" ],
      [ "ErrorValidator", "classcharliesoft_1_1_error_validator.html", "classcharliesoft_1_1_error_validator" ],
      [ "FileIsFolder", "classcharliesoft_1_1_file_is_folder.html", "classcharliesoft_1_1_file_is_folder" ],
      [ "ForBlock", "classcharliesoft_1_1_for_block.html", "classcharliesoft_1_1_for_block" ],
      [ "GlobalConfig", "classcharliesoft_1_1_global_config.html", "classcharliesoft_1_1_global_config" ],
      [ "GraphLayout", "classcharliesoft_1_1_graph_layout.html", "classcharliesoft_1_1_graph_layout" ],
      [ "GraphOfProcess", "classcharliesoft_1_1_graph_of_process.html", "classcharliesoft_1_1_graph_of_process" ],
      [ "GroupParamRepresentation", "classcharliesoft_1_1_group_param_representation.html", "classcharliesoft_1_1_group_param_representation" ],
      [ "ImageViewer", "classcharliesoft_1_1_image_viewer.html", "classcharliesoft_1_1_image_viewer" ],
      [ "Internationalizator", "classcharliesoft_1_1_internationalizator.html", "classcharliesoft_1_1_internationalizator" ],
      [ "LinkConnexionRepresentation", "classcharliesoft_1_1_link_connexion_representation.html", "classcharliesoft_1_1_link_connexion_representation" ],
      [ "LinkPath", "classcharliesoft_1_1_link_path.html", "classcharliesoft_1_1_link_path" ],
      [ "MainVertexBlock", "classcharliesoft_1_1_main_vertex_block.html", "classcharliesoft_1_1_main_vertex_block" ],
      [ "MainWidget", "classcharliesoft_1_1_main_widget.html", "classcharliesoft_1_1_main_widget" ],
      [ "MainWidget_ForGraph", "classcharliesoft_1_1_main_widget___for_graph.html", "classcharliesoft_1_1_main_widget___for_graph" ],
      [ "MainWidget_SubGraph", "classcharliesoft_1_1_main_widget___sub_graph.html", "classcharliesoft_1_1_main_widget___sub_graph" ],
      [ "Not_A_Value", "structcharliesoft_1_1_not___a___value.html", "structcharliesoft_1_1_not___a___value" ],
      [ "ParamDefinition", "structcharliesoft_1_1_param_definition.html", "structcharliesoft_1_1_param_definition" ],
      [ "ParamRepresentation", "classcharliesoft_1_1_param_representation.html", "classcharliesoft_1_1_param_representation" ],
      [ "ParamsConfigurator", "classcharliesoft_1_1_params_configurator.html", "classcharliesoft_1_1_params_configurator" ],
      [ "ParamValidator", "classcharliesoft_1_1_param_validator.html", "classcharliesoft_1_1_param_validator" ],
      [ "ParamValue", "classcharliesoft_1_1_param_value.html", "classcharliesoft_1_1_param_value" ],
      [ "ProcessManager", "classcharliesoft_1_1_process_manager.html", "classcharliesoft_1_1_process_manager" ],
      [ "SubBlock", "classcharliesoft_1_1_sub_block.html", "classcharliesoft_1_1_sub_block" ],
      [ "SubGraphParamRepresentation", "classcharliesoft_1_1_sub_graph_param_representation.html", "classcharliesoft_1_1_sub_graph_param_representation" ],
      [ "ValExclusif", "classcharliesoft_1_1_val_exclusif.html", "classcharliesoft_1_1_val_exclusif" ],
      [ "ValFileExist", "classcharliesoft_1_1_val_file_exist.html", "classcharliesoft_1_1_val_file_exist" ],
      [ "ValNeeded", "classcharliesoft_1_1_val_needed.html", "classcharliesoft_1_1_val_needed" ],
      [ "ValNegativ", "classcharliesoft_1_1_val_negativ.html", "classcharliesoft_1_1_val_negativ" ],
      [ "ValPositiv", "classcharliesoft_1_1_val_positiv.html", "classcharliesoft_1_1_val_positiv" ],
      [ "ValRange", "classcharliesoft_1_1_val_range.html", "classcharliesoft_1_1_val_range" ],
      [ "VertexRepresentation", "classcharliesoft_1_1_vertex_representation.html", "classcharliesoft_1_1_vertex_representation" ],
      [ "Window", "classcharliesoft_1_1_window.html", "classcharliesoft_1_1_window" ]
    ] ],
    [ "DefaultViewPort", "class_default_view_port.html", "class_default_view_port" ],
    [ "GraphViewer", "class_graph_viewer.html", "class_graph_viewer" ],
    [ "GuiReceiver", "class_gui_receiver.html", "class_gui_receiver" ],
    [ "MatrixViewer", "class_matrix_viewer.html", "class_matrix_viewer" ],
    [ "ToolsWindow", "class_tools_window.html", "class_tools_window" ],
    [ "ViewPort", "class_view_port.html", "class_view_port" ],
    [ "Zoomer", "class_zoomer.html", "class_zoomer" ]
];